export const SKILLS = {
  Core: ["JavaScript (ES6+)", "TypeScript", "HTML5", "CSS3"],
  Frameworks: ["ReactJS", "NextJS", "NodeJS", "ExpressJS"],
  "State Management": [
    "Redux",
    "MobX",
    "Zustand",
    "Context API",
    "React Query",
  ],
  "UI Libraries": [
    "Material UI",
    "Mantine UI",
    "Tailwind CSS",
    "Bootstrap",
    "Styled Components",
    "Framer Motion",
  ],
  Testing: ["Jest", "Cypress", "Playwright", "Vitest", "React Testing Library"],
  Geospatial: ["MapBox", "CesiumJS", "React-Konva", "kr-pano"],
  "DevOps & Tools": [
    "Docker",
    "CI/CD",
    "Git",
    "Github Actions",
    "Nx",
    "Webpack",
    "Vite",
  ],
  "Databases & APIs": ["MongoDB", "REST APIs", "WebSockets", "Socket.io"],
  Other: [
    "Performance Optimization",
    "Cross-Browser Compatibility",
    "Web Security",
    "Web Accessibility (a11y)",
    "PWA",
    "SPA",
    "AWS",
  ],
}
