export const SKILLS = [
  "AWS",
  "axios",
  "Bootstrap",
  "CesiumJS",
  "CI/CD",
  "Context API",
  "CSS",
  "CSS3",
  "Cypress",
  "Docker",
  "ExpressJS",
  "Formik",
  "Framer motion",
  "Git",
  "Github Actions",
  "HTML",
  "HTML5",
  "JavaScript (ES6+)",
  "Jest",
  "kr-pano",
  "Mantine UI",
  "MapBox",
  "Material UI",
  "MongoDB",
  "NextJS",
  "NodeJS",
  "Nx",
  "Playwright",
  "React Hook Form",
  "React Query",
  "React Router",
  "React Table",
  "React Testing Library (RTL)",
  "React-Konva",
  "ReactJS",
  "Recharts",
  "Redux/MobX/Flux/Zustand",
  "REST APIs",
  "Socket.io",
  "Styled Components",
  "Tailwind CSS",
  "TypeScript",
  "Web3.js",
  "Yup",
  "Performance Optimization",
  "Cross-Browser Compatibility",
  "PWA",
  "SPA",
  "Unit/Integration/E2E Testing",
  "Vite",
  "Vitest",
  "Webpack",
  "Debugging",
  "Git",
  "Web Security",
  "Web Accessibility (a11y)",
  "WebSockets",
]
